# constants.py
CONNECTION_DB_USER = "CONNECTION_DB_USER"
CONNECTION_DB_PRODUCT = "CONNECTION_DB_PRODUCT"

PATH_DB_USER = "./src/repositories/db/db_user.db"
PATH_DB_PRODUCT = "./src/repositories/db/db_product.db"

TABLE_USER = "TABLE_USER"
TABLE_RE_PRODUCT = "TABLE_RE_PRODUCT"
TABLE_RE_TEMPLATE = "TABLE_RE_TEMPLATE"
TABLE_LISTED_PRODUCT = "TABLE_LISTED_PRODUCT"
TABLE_MISC_PRODUCT = "TABLE_MISC_PRODUCT"
TABLE_USER_SETTING_UDD = "TABLE_USER_SETTING_UDD"
TABLE_USER_SETTING_PROXY = "TABLE_USER_SETTING_PROXY"
